sonar.projectKey=fga-eps-mds_2026.1-MeasureSoftGram-CLI
sonar.organization=fga-eps-mds-1
sonar.python.version=3.10

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__init__.py,**/setup_log.py,**/parsers.py,**/cli.py
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml